[workspace]
members = ["tycho-indexer", "substreams/ethereum-ambient"]
resolver = "2"

# profile for building substreams crates
[profile.substreams]
inherits = "release"
lto = true
opt-level = 'z'
strip = "debuginfo"
