version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: tycho_indexer_0
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
  tycho-indexer:
    image: ${TYCHO_IMAGE}
    restart: always
    environment:
      SUBSTREAMS_API_TOKEN: ""
      DATABASE_URL: "postgres://postgres:mypassword@localhost:5432/tycho_indexer_0"