version: '3.1'
services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: tycho_indexer_0
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
  tycho-indexer:
    image: ${TYCHO_IMAGE}
    restart: no
    depends_on:
    - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      SUBSTREAMS_API_TOKEN: changeme
      STREAMINGFAST_KEY: changeme
      DATABASE_URL: postgres://postgres:mypassword@db:5432/tycho_indexer_0
      START_BLOCK: 17361664
      STOP_BLOCK: 0
      RUST_LOG: info
    ports:
      - "4242:4242"
    volumes:
      - ./wait-for-postgres.sh:/usr/wait-for-postgres.sh
    entrypoint: ["/usr/wait-for-postgres.sh", "db"]
    command: ["/opt/tycho-indexer/tycho-indexer", "--endpoint", "https://mainnet.eth.streamingfast.io:443", "--module", "map_changes", "--spkg", "/opt/tycho-indexer/substreams/substreams-ethereum-ambient-v0.3.0.spkg"]