# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/postgres/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId"]
filter = { except_tables = ["component_balance", "protocol_state", "contract_storage"] }

[migrations_directory]
dir = "migrations"
