[package]
name = "tycho-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures03.workspace = true
thiserror.workspace = true
tracing.workspace = true
tycho-msg-types.workspace = true
hyper.workspace = true
async-trait.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
hex.workspace = true


[dev-dependencies]
mockito = "1.1.1"
tungstenite = "0.20.1"
