name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  upload-assets:
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: universal-apple-darwin
            os: macos-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
        package: [tycho-client, tycho-indexer]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install PostgreSQL Client on macOS
        if: runner.os == 'macOS'
        run: |
          brew install libpq
          brew link --force libpq
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ${{ matrix.package }}
          archive: ${{ matrix.package }}-${{ matrix.target }}-${{ github.event.release.tag_name }}
          target: ${{ matrix.target }}
          tar: all
          zip: none
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: 'arn:aws:iam::827659017777:role/github-actions'
          audience: sts.amazonaws.com
          aws-region: eu-central-1
      - name: Upload binary to S3
        run: |
          FILE_NAME=${{ matrix.package }}-${{ matrix.target }}-${{ github.event.release.tag_name }}.tar.gz
          BUCKET_NAME=repo.propellerheads/tycho-client
          aws s3 cp $FILE_NAME s3://$BUCKET_NAME/$FILE_NAME
