name: Main workflow

on:
  push:
    branches:
      - fix/update-dockerfile

jobs:
  build-and-push:
    uses: propeller-heads/ci-cd-templates/.github/workflows/build-and-push-docker-image.yaml@main
    permissions:
      id-token: write
      contents: read
    with:
      image_tag: testdockerfileupdatetag
      image_name: tycho-indexer
    secrets:
      app_id: ${{ secrets.APP_ID }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
      role_to_assume: ${{ secrets.ROLE_TO_ASSUME }}
      aws_region: ${{ secrets.AWS_REGION }}
      repository_url: ${{ secrets.REPOSITORY_URL }}
      domain_owner: ${{ secrets.DOMAIN_OWNER }}
