name: Publish Python Package

on:
  release:
    types:
      - prereleased
      - released
  workflow_dispatch: { }

permissions:
  id-token: write
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  publish_tycho_indexer_client:
    uses: propeller-heads/ci-cd-templates/.github/workflows/release-python-package.yaml@main
    permissions:
      id-token: write
      contents: read
    with:
      package_root: "tycho-client-py"
    secrets:
      app_id: ${{ secrets.APP_ID }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}